### ISSUE TITLE
Mouseover of some image blocks causes image to shift

### ISSUE THREAD

**Issue by dpetersen** [pootychop/pootychop.github.io#3]
If you visit [the portfolio section of your website](http://juliannabeckert.com/#portfolio) and mouseover the Goat Suitcase (in Chrome, untested in other browsers) you will notice that the goat shifts over a few pixels. Ice Cream will shift down. Not all images do this, but many do.

![Sad Cat.](http://i258.photobucket.com/albums/hh253/jimifunguzz/cat%20gifs/cat-sad-cat.gif)

**Comment by pootychop** [comment]
Hey. Thanks.

I saw that but I wasn't sure what to do about it. I forget what it was
called that I put on them, something like a box transform or some shit
that's supposed to make the border go inside the the container rather than
adding pixels... That's working, but yeah. It shifts some images and not
others. I'll try to figure that out tonight.

On Friday, January 2, 2015, Don Petersen <notifications@github.com> wrote:

> If you visit the portfolio section of your website
> <http://juliannabeckert.com/#portfolio> and mouseover the Goat Suitcase
> (in Chrome, untested in other browsers) you will notice that the goat
> shifts over a few pixels. Ice Cream will shift down. Not all images do
> this, but many do.
>
> [image: Sad Cat.]
> <https://camo.githubusercontent.com/e80e99b119d32d3e0ac824532c87d8de5b472cfb/687474703a2f2f693235382e70686f746f6275636b65742e636f6d2f616c62756d732f68683235332f6a696d6966756e67757a7a2f636174253230676966732f6361742d7361642d6361742e676966>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pootychop/pootychop.github.io/issues/3>.
>


-- 
Julianna Beckert
918-845-5854
juliannabeckert.com
